# Generated by Django 4.0 on 2021-12-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('center', models.CharField(max_length=30)),
                ('meter1', models.CharField(max_length=30)),
            ],
        ),
    ]
