# Generated by Django 4.0 on 2021-12-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedata',
            old_name='bdate',
            new_name='bdates',
        ),
    ]
