# Generated by Django 4.0 on 2021-12-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_bdate_savedata_bdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedata',
            old_name='bdates',
            new_name='bdate',
        ),
    ]
