# Generated by Django 4.0 on 2021-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_bdates_savedata_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedata',
            name='bdate',
            field=models.DateField(auto_now=True),
        ),
    ]
