# Generated by Django 4.0 on 2021-12-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_savedata_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedata',
            name='bdate',
            field=models.DateField(),
        ),
    ]
