# Generated by Django 4.0 on 2021-12-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_savedata_bdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saveData',
            new_name='saveData1',
        ),
    ]
